name: mask_text_input_formatter
description: Mask Text Input Formatter
version: 1.0.0
author: Sergey Smurov
homepage: https://github.com/siqwin/mask_text_input_formatter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

